### ISSUE TITLE
alphashape error

### ISSUE THREAD

**Issue by MBalazs90** [anitagraser/pgRoutingLayer#10]
when I run I always got this error:

Traceback (most recent call last):
  File "C:/Users/M/.qgis2/python/plugins\pgRoutingLayer\pgRoutingLayer.py", line 391, in run
    function.draw(rows, con, args, geomType, self.canvasItemList, self.iface.mapCanvas())
  File "C:/Users/M/.qgis2/python/plugins\pgRoutingLayer\functions\alphashape.py", line 88, in draw
    pt = QgsPoint(x, y)
TypeError: arguments did not match any overloaded call:
  QgsPoint(): too many arguments
  QgsPoint(QgsPoint): argument 1 has unexpected type 'NoneType'
  QgsPoint(float, float): argument 1 has unexpected type 'NoneType'
  QgsPoint(QPointF): argument 1 has unexpected type 'NoneType'
  QgsPoint(QPoint): argument 1 has unexpected type 'NoneType'``

whats the problem?

**Comment by sanak** [comment]
@MBalazs90 
I guess that `x` is `None`, but I am not sure why it happens.
By the way, which pgRouting version are you using ?

**Comment by MBalazs90** [comment]
im using the 2.1.0 version

**Comment by sanak** [comment]
@MBalazs90 
Okay, thanks for confirmation.
I am still working to support pgRouting >= 2.1.0 on https://github.com/pgRouting/pgRoutingLayer/tree/pgr-2.1.0 branch,
so it (pgRouting version difference) may cause the issue.
Now, I am a bit busy with regular work, so I will check it from next month.
If you are in a hurry, please consider to use previous pgRouting version (2.0).

**Comment by MBalazs90** [comment]
okay, thanks :+1:
