### ISSUE TITLE
Error when calling its classFactory() method 

### ISSUE THREAD

**Issue by salilrsharma** [anitagraser/pgRoutingLayer#21]
Hi,

I am getting the following error while installing the plugin from the zip file within QGIS 3. I woudl appreciate if you coudl take a look at the issue.

Thanks,
Salil
----------------------------------
Couldn't load plugin 'pgRoutingLayer-master' due to an error when calling its classFactory() method 

ImportError: cannot import name 'PgRoutingLayer' 
Traceback (most recent call last):
  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 337, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "D:/salilsharma/Application data/QGIS/QGIS3\profiles\default/python/plugins\pgRoutingLayer-master\__init__.py", line 35, in classFactory
    from pgRoutingLayer import PgRoutingLayer
ImportError: cannot import name 'PgRoutingLayer'

Python version: 3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 08:06:12) [MSC v.1900 64 bit (AMD64)] 
QGIS version: 3.2.3-Bonn Bonn, 9b176802e5 

Python Path:
C:/OSGEO4~1/apps/qgis/./python
D:/salilsharma/Application data/QGIS/QGIS3\profiles\default/python
D:/salilsharma/Application data/QGIS/QGIS3\profiles\default/python/plugins
C:/OSGEO4~1/apps/qgis/./python/plugins
C:\OSGeo4W64\bin\python36.zip
C:\OSGEO4~1\apps\Python36\DLLs
C:\OSGEO4~1\apps\Python36\lib
C:\OSGeo4W64\bin
C:\OSGEO4~1\apps\Python36
C:\OSGEO4~1\apps\Python36\lib\site-packages
C:\OSGEO4~1\apps\Python36\lib\site-packages\win32
C:\OSGEO4~1\apps\Python36\lib\site-packages\win32\lib
C:\OSGEO4~1\apps\Python36\lib\site-packages\Pythonwin
D:/salilsharma/Application data/QGIS/QGIS3\profiles\default/python

**Comment by Aurora1203** [comment]
similar issue, anyone knows the solution?

Couldn't load plugin 'rastertool' due to an error when calling its classFactory() method 

ModuleNotFoundError: No module named 'pyrsgis' 
Traceback (most recent call last):
  File "C:/PROGRA~1/QGIS3~1.14/apps/qgis/./python\qgis\utils.py", line 334, in _startPlugin
    plugins[packageName] = package.classFactory(iface)

**Comment by anitagraser** [comment]
This plugin is now maintained by the PgRouting team.

Project home and bug tracker has moved to https://github.com/pgRouting/pgRoutingLayer.
